
import { Graduate, Course, Status, User } from './types';

export const MOCK_GRADUATES: Graduate[] = [
  {
    id: '1',
    nome: 'Ana Silva',
    anoIngresso: 2018,
    anoDefesa: 2020,
    orientador: 'Dr. Carlos Pereira',
    tituloDefesa: 'Análise de Algoritmos de Machine Learning',
    curso: Course.MESTRADO,
    status: Status.DEFENDIDO,
    cursandoDoutorado: true,
    trabalhando: 'Google',
    trabalhandoOutroEstado: true,
  },
  {
    id: '2',
    nome: 'Bruno Costa',
    anoIngresso: 2019,
    anoDefesa: 2021,
    orientador: 'Dra. Beatriz Lima',
    tituloDefesa: 'Desenvolvimento de um Sistema Distribuído',
    curso: Course.MESTRADO,
    status: Status.DEFENDIDO,
    cursandoDoutorado: false,
    trabalhando: 'Microsoft',
    trabalhandoOutroEstado: false,
  },
  {
    id: '3',
    nome: 'Carla Dias',
    anoIngresso: 2017,
    anoDefesa: 2021,
    orientador: 'Dr. João Mendes',
    tituloDefesa: 'Redes Neurais Profundas para Visão Computacional',
    curso: Course.DOUTORADO,
    status: Status.DEFENDIDO,
    cursandoDoutorado: false,
    trabalhando: 'NVIDIA',
    trabalhandoOutroEstado: true,
  },
  {
    id: '4',
    nome: 'Daniel Martins',
    anoIngresso: 2022,
    orientador: 'Dr. Carlos Pereira',
    tituloDefesa: 'Estudo sobre Criptografia Quântica',
    curso: Course.MESTRADO,
    status: Status.CURSANDO,
    cursandoDoutorado: false,
    trabalhandoOutroEstado: false,
  },
  {
    id: '5',
    nome: 'Eduarda Ferreira',
    anoIngresso: 2020,
    anoDefesa: 2022,
    orientador: 'Dra. Beatriz Lima',
    tituloDefesa: 'Otimização de Compiladores',
    curso: Course.MESTRADO,
    status: Status.DEFENDIDO,
    cursandoDoutorado: true,
    trabalhando: 'Oracle',
    trabalhandoOutroEstado: false,
  },
  {
    id: '6',
    nome: 'Fábio Gomes',
    anoIngresso: 2021,
    orientador: 'Dr. João Mendes',
    tituloDefesa: 'Modelagem de Sistemas Complexos',
    curso: Course.DOUTORADO,
    status: Status.CURSANDO,
    cursandoDoutorado: false,
    trabalhando: 'IBM',
    trabalhandoOutroEstado: false,
  },
   {
    id: '7',
    nome: 'Gabriela Rocha',
    anoIngresso: 2019,
    anoDefesa: 2023,
    orientador: 'Dr. Carlos Pereira',
    tituloDefesa: 'Inteligência Artificial em Jogos Digitais',
    curso: Course.DOUTORADO,
    status: Status.DEFENDIDO,
    cursandoDoutorado: false,
    trabalhando: 'Ubisoft',
    trabalhandoOutroEstado: true,
  },
  {
    id: '8',
    nome: 'Heitor Almeida',
    anoIngresso: 2023,
    orientador: 'Dra. Beatriz Lima',
    tituloDefesa: 'Computação em Nuvem e Serverless',
    curso: Course.MESTRADO,
    status: Status.CURSANDO,
    cursandoDoutorado: false,
    trabalhandoOutroEstado: false,
  }
];

export const MOCK_USERS: User[] = [
    { id: 'u1', name: 'Admin User', email: 'admin@example.com', role: 'Admin' },
    { id: 'u2', name: 'Viewer User', email: 'viewer@example.com', role: 'Viewer' },
];

export const PT_BR_MONTHS = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'];
